export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type SupabaseTableShape = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: never[];
};

export type Database = {
  public: {
    Tables: {
      raiz_checkins: {
        Row: {
          checkin_date: string;
          completed_steps: Json;
          created_at: string;
          daily_note: string;
          definition_score: number;
          ends_score: number;
          focus_label: string;
          humidity: number;
          hydration_score: number;
          id: string;
          overall_score: number;
          photo_logged: boolean;
          selected_habits: string[];
          selected_product_ids: string[];
          selected_symptoms: string[];
          strength_score: number;
          summary_description: string;
          summary_title: string;
          temperature: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          checkin_date?: string;
          completed_steps?: Json;
          created_at?: string;
          daily_note?: string;
          definition_score?: number;
          ends_score?: number;
          focus_label?: string;
          humidity?: number;
          hydration_score?: number;
          id?: string;
          overall_score?: number;
          photo_logged?: boolean;
          selected_habits?: string[];
          selected_product_ids?: string[];
          selected_symptoms?: string[];
          strength_score?: number;
          summary_description?: string;
          summary_title?: string;
          temperature?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          checkin_date?: string;
          completed_steps?: Json;
          created_at?: string;
          daily_note?: string;
          definition_score?: number;
          ends_score?: number;
          focus_label?: string;
          humidity?: number;
          hydration_score?: number;
          id?: string;
          overall_score?: number;
          photo_logged?: boolean;
          selected_habits?: string[];
          selected_product_ids?: string[];
          selected_symptoms?: string[];
          strength_score?: number;
          summary_description?: string;
          summary_title?: string;
          temperature?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: never[];
      };
      raiz_products: {
        Row: {
          brand: string | null;
          category: string;
          created_at: string;
          id: string;
          is_active: boolean;
          name: string;
          purpose: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          brand?: string | null;
          category: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name: string;
          purpose?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          brand?: string | null;
          category?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name?: string;
          purpose?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: never[];
      };
      raiz_profiles: {
        Row: {
          age_range: string | null;
          blow_dryer_frequency: string;
          care_frequency: string;
          chemical_processes: string[];
          climate_impacts_hair: boolean | null;
          city_or_region: string | null;
          consistency_feeling: string | null;
          created_at: string;
          current_goals: string[];
          current_length: string | null;
          density: string;
          desired_day_to_day_results: string[];
          display_name: string;
          feelings_about_hair: string[];
          flat_iron_frequency: string;
          gender_identity: string | null;
          hair_type: string;
          hair_knowledge_level: string | null;
          is_transitioning: boolean;
          main_challenges: string[];
          nighttime_habits: string[];
          notes: string | null;
          onboarding_completed_at: string | null;
          porosity: string;
          protective_styles: string[];
          protective_style_duration: string | null;
          recurring_symptoms: string[];
          region_climate: string;
          reminders_enabled: boolean;
          scalp_oiliness: string;
          sleeps_with_bonnet: boolean;
          routine_preference: string | null;
          time_available: string | null;
          texture: string;
          updated_at: string;
          user_id: string;
          uses_hair_protection: boolean;
          volume_perception: string | null;
          wash_frequency: string;
          washes_while_protective_style: boolean | null;
        };
        Insert: {
          age_range?: string | null;
          blow_dryer_frequency?: string;
          care_frequency: string;
          chemical_processes?: string[];
          climate_impacts_hair?: boolean | null;
          city_or_region?: string | null;
          consistency_feeling?: string | null;
          created_at?: string;
          current_goals?: string[];
          current_length?: string | null;
          density: string;
          desired_day_to_day_results?: string[];
          display_name: string;
          feelings_about_hair?: string[];
          flat_iron_frequency?: string;
          gender_identity?: string | null;
          hair_type: string;
          hair_knowledge_level?: string | null;
          is_transitioning?: boolean;
          main_challenges?: string[];
          nighttime_habits?: string[];
          notes?: string | null;
          onboarding_completed_at?: string | null;
          porosity: string;
          protective_styles?: string[];
          protective_style_duration?: string | null;
          recurring_symptoms?: string[];
          region_climate: string;
          reminders_enabled?: boolean;
          scalp_oiliness: string;
          sleeps_with_bonnet?: boolean;
          routine_preference?: string | null;
          time_available?: string | null;
          texture: string;
          updated_at?: string;
          user_id: string;
          uses_hair_protection?: boolean;
          volume_perception?: string | null;
          wash_frequency: string;
          washes_while_protective_style?: boolean | null;
        };
        Update: {
          age_range?: string | null;
          blow_dryer_frequency?: string;
          care_frequency?: string;
          chemical_processes?: string[];
          climate_impacts_hair?: boolean | null;
          city_or_region?: string | null;
          consistency_feeling?: string | null;
          created_at?: string;
          current_goals?: string[];
          current_length?: string | null;
          density?: string;
          desired_day_to_day_results?: string[];
          display_name?: string;
          feelings_about_hair?: string[];
          flat_iron_frequency?: string;
          gender_identity?: string | null;
          hair_type?: string;
          hair_knowledge_level?: string | null;
          is_transitioning?: boolean;
          main_challenges?: string[];
          nighttime_habits?: string[];
          notes?: string | null;
          onboarding_completed_at?: string | null;
          porosity?: string;
          protective_styles?: string[];
          protective_style_duration?: string | null;
          recurring_symptoms?: string[];
          region_climate?: string;
          reminders_enabled?: boolean;
          scalp_oiliness?: string;
          sleeps_with_bonnet?: boolean;
          routine_preference?: string | null;
          time_available?: string | null;
          texture?: string;
          updated_at?: string;
          user_id?: string;
          uses_hair_protection?: boolean;
          volume_perception?: string | null;
          wash_frequency?: string;
          washes_while_protective_style?: boolean | null;
        };
        Relationships: never[];
      };
    };
    Views: Record<string, never>;
    Functions: Record<
      string,
      {
        Args: Record<string, Json | undefined>;
        Returns: Json | Record<string, unknown> | Array<Record<string, unknown>> | null;
      }
    >;
    Enums: Record<string, string>;
    CompositeTypes: Record<string, never>;
  };
};
